<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-E716VJT" ignored="0" name="Default test(failed)" tests="2" failures="2" timestamp="2022-06-17T16:41:18 IST" time="9.197" errors="0">
  <testcase name="VerifyLogin" time="2.407" classname="com.selenium.basictest.HardAssertion_practice">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Altoro Mutual11] but found [Altoro Mutual]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Altoro Mutual11] but found [Altoro Mutual]
at com.selenium.basictest.HardAssertion_practice.VerifyLogin(HardAssertion_practice.java:59)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- VerifyLogin -->
  <testcase name="VerifyMainPage" time="4.374" classname="com.selenium.basictest.HardAssertion_practice">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Altoro Mutual11] but found [Altoro Mutual]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Altoro Mutual11] but found [Altoro Mutual]
at com.selenium.basictest.HardAssertion_practice.VerifyMainPage(HardAssertion_practice.java:75)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- VerifyMainPage -->
</testsuite> <!-- Default test(failed) -->
